[build]
  command = "bun run build"
  publish = "dist/iswavle/browser"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/doc/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/exercises"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/exercises/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/playground"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/playground/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
