[build]
  command = "bun run build"
  publish = "dist/iswavle/browser"
[build.environment]
  NODE_VERSION = "20"
[[plugins]]
  package = "@netlify/plugin-angular"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"