import { MetaConfig } from '@app-shared/interfaces';

export const TITLE_SUFFIX = 'Iswavle';
export const TITLE_SEPARATOR = '•';
export const TITLE_SUFFIX_SEPARATOR = '|';

export const DEFAULT_KEYWORDS = ['iswavle, educata, ისწავლე, ისწავლე ვები'];

export const DEFAULT_META_CONFIG: MetaConfig[] = [
  {
    name: 'html-css',
    keywords: [
      'html',
      'css',
      'ჰტმლ',
      'ცსს',
      'forms',
      'სტილიზაციები',
      'html5',
      'css3',
      'semantic html',
      'responsive design',
      'flexbox',
      'grid',
      'sass',
      'scss',
      'less',
      'postcss',
    ],
    imagePath: 'banner_iswavle_html_css.jpg',
  },
  {
    name: 'scss',
    keywords: [],
    imagePath: 'sass.png',
  },
  {
    name: 'javascript',
    keywords: [
      'js',
      'javascript',
      'ჯავასკრიპტი',
      'ჯავასკრიპტის გზამკვლევი',
      'variables',
      'functions',
      'objects',
      'arrays',
      'loops',
      'conditionals',
      'errors',
      'debugging',
      'performance',
      'optimization',
      'best practices',
      'testing',
      'performance',
      'optimization',
      'best practices',
    ],
    imagePath: 'banner_iswavle_js.jpg',
  },
  {
    name: 'client-side-tools',
    keywords: [
      'webpack',
      'gulp',
      'npm',
      'yarn',
      'parcel',
      'rollup',
      'vite',
      'esbuild',
      'tsc',
      'eslint',
      'prettier',
      'stylelint',
    ],
    imagePath: 'banner_iswavle_tools.jpg',
  },
  {
    name: 'typescript',
    keywords: [
      'ts',
      'typescript',
      'ტაიპსკრიპტი',
      'ტაიპსკრიპტის გზამკვლევი',
      'types',
      'enums',
      'interfaces',
      'generics',
      'decorators',
      'async/await',
      'promises',
      'testing',
      'performance',
      'optimization',
      'best practices',
    ],
    imagePath: 'banner_iswavle_ts.jpg',
  },
  {
    name: 'angular',
    keywords: [
      'angular',
      'ანგულარი',
      'ანგულარის გზამკვლევი',
      'SPA',
      'dependency injection',
      'rxjs',
      'pipes',
      'directives',
      'components',
      'services',
      'routing',
      'forms',
      'http',
      'testing',
      'performance',
    ],
    imagePath: 'banner_iswavle_angular.jpg',
  },
];
